vim.g.mapleader = " "
vim.cmd("set clipboard=unnamedplus")
vim.cmd("set hidden")
vim.cmd("set mouse=a")
vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set cursorline")
